#include "VolumeSound.hpp"
#include "globals.hpp"

#include <hyprland/src/Compositor.hpp>

#include <atomic>
#include <chrono>
#include <cstdio>
#include <cstring>
#include <cstdint>
#include <fcntl.h>
#include <poll.h>
#include <string>
#include <string_view>
#include <thread>
#include <unistd.h>
#include <unordered_map>

// Embedded WAV data generated by CMake (xxd -i volume.wav)
extern unsigned char volume_wav[];
extern unsigned int  volume_wav_len;

// ── Static members ─────────────────────────────────────────────────────────

CHyprSignalListener VolumeSound::s_keyListener;

namespace {

// ── Audio thread state ─────────────────────────────────────────────────────

std::thread       s_audioThread;
std::atomic<bool> s_running{false};
int               s_pipeRead  = -1;
int               s_pipeWrite = -1;

static const char TEMP_WAV[] = "/tmp/hyprmac_volume.wav";

// ── Volume cache (audio thread only) ──────────────────────────────────────

float      s_volCache      = 1.0f;
bool       s_muteCache     = false;
auto       s_volCacheTime  = std::chrono::steady_clock::now() - std::chrono::seconds(10);
const auto CACHE_TTL       = std::chrono::milliseconds(100);

// Returns system volume as 0.0–1.0, cached.
float systemVolume(bool forceRefresh = false) {
    const auto now = std::chrono::steady_clock::now();
    if (!forceRefresh && now - s_volCacheTime < CACHE_TTL)
        return s_muteCache ? 0.0f : s_volCache;
    s_volCacheTime = now;

    // Check mute
    {
        FILE* f = popen("pactl get-sink-mute @DEFAULT_SINK@ 2>/dev/null", "r");
        if (f) {
            char buf[64] = {};
            fgets(buf, sizeof(buf), f);
            pclose(f);
            s_muteCache = (std::string_view{buf}.find("yes") != std::string_view::npos);
        }
    }

    // Get volume percentage
    {
        FILE* f = popen("pactl get-sink-volume @DEFAULT_SINK@ 2>/dev/null", "r");
        if (f) {
            char buf[256] = {};
            fgets(buf, sizeof(buf), f);
            pclose(f);
            // "Volume: front-left: 32768 /  50% / ..."
            const char* p = strstr(buf, "/ ");
            if (p) {
                int pct = 0;
                if (sscanf(p + 2, "%d%%", &pct) == 1)
                    s_volCache = pct / 100.0f;
            }
        }
    }

    return s_muteCache ? 0.0f : s_volCache;
}

// ── Playback (audio thread only) ──────────────────────────────────────────

void playSound() {
    const float sysVol = systemVolume(true);

    if (sysVol < 0.01f)
        return; // muted or effectively silent — skip

    // Keep the click audible at very low system volumes, while capping the
    // stream gain so we do not blast the user when they are near 0%.
    constexpr float    MIN_FLOOR = 0.35f;
    constexpr float    MAX_GAIN  = 10.0f;
    const float        gain      = (sysVol < MIN_FLOOR)
                                       ? std::min(MIN_FLOOR / sysVol, MAX_GAIN)
                                       : 1.0f;
    const uint32_t     paVol     = static_cast<uint32_t>(gain * 65536.0f);

    char cmd[256];
    snprintf(cmd, sizeof(cmd),
             "paplay --client-name=hyprmac-volume-$$ --volume=%u %s >/dev/null 2>&1 &",
             paVol, TEMP_WAV);

    system(cmd); // NOLINT — intentional, runs in audio thread only
}

// ── Audio thread main loop ─────────────────────────────────────────────────

void audioThreadMain() {
    while (s_running.load(std::memory_order_acquire)) {
        struct pollfd pfd{s_pipeRead, POLLIN, 0};
        if (poll(&pfd, 1, 50) <= 0)
            continue;

        char buf[16];
        const ssize_t n = read(s_pipeRead, buf, sizeof(buf));
        for (ssize_t i = 0; i < n; i++) {
            if (buf[i] == 1)
                playSound();
        }
    }
}

} // namespace

// ── Config helper (mirrors CapsLockIndicator pattern) ─────────────────────

int VolumeSound::configInt(const std::string& key) {
    static std::unordered_map<std::string, Hyprlang::INT* const*> cache;
    auto it = cache.find(key);
    if (it == cache.end()) {
        auto* cv = HyprlandAPI::getConfigValue(PHANDLE, key);
        if (!cv)
            return 0;
        cache[key] = (Hyprlang::INT* const*)cv->getDataStaticPtr();
        it         = cache.find(key);
    }
    return (int)**it->second;
}

// ── Event handler (main thread — only writes to pipe) ─────────────────────

void VolumeSound::onKey(IKeyboard::SKeyEvent ev, Event::SCallbackInfo& info) {
    (void)info;

    // KEY_VOLUMEUP = 115, KEY_VOLUMEDOWN = 114 (Linux evdev)
    if (ev.keycode != 115 && ev.keycode != 114)
        return;

    if (!configInt("plugin:hyprmac:volume_sound_enabled"))
        return;

    if (ev.state != WL_KEYBOARD_KEY_STATE_RELEASED)
        return;

    // Match macOS behavior: adjust silently while the key is held, then play
    // one click on release at the final volume level.
    const char sig = 1;
    write(s_pipeWrite, &sig, 1);
}

// ── Lifecycle ──────────────────────────────────────────────────────────────

void VolumeSound::init() {
    // Write embedded WAV to temp file once so paplay can read it
    if (FILE* f = fopen(TEMP_WAV, "wb")) {
        fwrite(volume_wav, 1, volume_wav_len, f);
        fclose(f);
    }

    int fds[2];
    if (pipe(fds) != 0)
        return;
    s_pipeRead  = fds[0];
    s_pipeWrite = fds[1];
    fcntl(s_pipeWrite, F_SETFL, O_NONBLOCK);

    s_running.store(true, std::memory_order_release);
    s_audioThread = std::thread(audioThreadMain);

    s_keyListener = Event::bus()->m_events.input.keyboard.key.listen(
        [](IKeyboard::SKeyEvent ev, Event::SCallbackInfo& info) { onKey(ev, info); }
    );
}

void VolumeSound::destroy() {
    s_keyListener.reset();

    s_running.store(false, std::memory_order_release);
    if (s_pipeWrite >= 0) {
        const char wake = 0;
        write(s_pipeWrite, &wake, 1);
    }
    if (s_audioThread.joinable())
        s_audioThread.join();

    if (s_pipeRead  >= 0) { close(s_pipeRead);  s_pipeRead  = -1; }
    if (s_pipeWrite >= 0) { close(s_pipeWrite); s_pipeWrite = -1; }

    unlink(TEMP_WAV);
}
