#include "VolumeSound.hpp"
#include "globals.hpp"
#include "deps/miniaudio.h"

#include <hyprland/src/Compositor.hpp>

#include <atomic>
#include <chrono>
#include <cstdio>
#include <fcntl.h>
#include <poll.h>
#include <string>
#include <string_view>
#include <thread>
#include <unistd.h>
#include <unordered_map>
#include <vector>

// Embedded WAV data generated by CMake (xxd -i volume.wav)
extern unsigned char volume_wav[];
extern unsigned int  volume_wav_len;

// ── Static members ─────────────────────────────────────────────────────────

CHyprSignalListener VolumeSound::s_keyListener;

namespace {

// ── Audio thread state ─────────────────────────────────────────────────────

std::thread          s_audioThread;
std::atomic<bool>    s_running{false};
int                  s_pipeRead  = -1;
int                  s_pipeWrite = -1;

ma_engine            s_engine;
bool                 s_engineReady = false;

// ── Mute state cache (audio thread only) ──────────────────────────────────

bool       s_muteCache     = false;
auto       s_muteCacheTime = std::chrono::steady_clock::now() - std::chrono::seconds(10);
const auto MUTE_CACHE_TTL  = std::chrono::milliseconds(500);

bool isMuted() {
    const auto now = std::chrono::steady_clock::now();
    if (now - s_muteCacheTime < MUTE_CACHE_TTL)
        return s_muteCache;
    s_muteCacheTime = now;

    FILE* f = popen("pactl get-sink-mute @DEFAULT_SINK@ 2>/dev/null", "r");
    if (!f)
        return false;
    char buf[64] = {};
    fgets(buf, sizeof(buf), f);
    pclose(f);
    s_muteCache = (std::string_view{buf}.find("yes") != std::string_view::npos);
    return s_muteCache;
}

// ── One-shot playback (audio thread only) ─────────────────────────────────

struct PlayInstance {
    ma_decoder        decoder;
    ma_sound          sound;
    std::atomic<bool> finished{false};
};

std::vector<PlayInstance*> s_playInstances;

void cleanupFinishedSounds(bool all = false) {
    auto it = s_playInstances.begin();
    while (it != s_playInstances.end()) {
        auto* inst = *it;
        if (!all && !inst->finished.load(std::memory_order_acquire)) {
            ++it;
            continue;
        }
        ma_sound_uninit(&inst->sound);
        ma_decoder_uninit(&inst->decoder);
        delete inst;
        it = s_playInstances.erase(it);
    }
}

void playSound() {
    if (!s_engineReady)
        return;

    cleanupFinishedSounds();

    auto* inst = new PlayInstance{};

    const ma_decoder_config cfg = ma_decoder_config_init_default();
    if (ma_decoder_init_memory(volume_wav, volume_wav_len, &cfg, &inst->decoder) != MA_SUCCESS) {
        delete inst;
        return;
    }

    if (ma_sound_init_from_data_source(&s_engine, &inst->decoder,
            MA_SOUND_FLAG_NO_SPATIALIZATION, nullptr, &inst->sound) != MA_SUCCESS) {
        ma_decoder_uninit(&inst->decoder);
        delete inst;
        return;
    }

    s_playInstances.push_back(inst);

    ma_sound_set_end_callback(&inst->sound, [](void* ud, ma_sound*) {
        static_cast<PlayInstance*>(ud)->finished.store(true, std::memory_order_release);
    }, inst);

    ma_sound_start(&inst->sound);
}

// ── Audio thread main loop ─────────────────────────────────────────────────

void audioThreadMain() {
    // All PipeWire/PulseAudio IPC happens here — never on the compositor main thread
    const ma_engine_config cfg = ma_engine_config_init();
    if (ma_engine_init(&cfg, &s_engine) != MA_SUCCESS)
        return;
    s_engineReady = true;

    while (s_running.load(std::memory_order_acquire)) {
        struct pollfd pfd{s_pipeRead, POLLIN, 0};
        if (poll(&pfd, 1, 50) <= 0)
            continue;

        char buf[16];
        const ssize_t n = read(s_pipeRead, buf, sizeof(buf));
        for (ssize_t i = 0; i < n; i++) {
            if (buf[i] == 1 && !isMuted())
                playSound();
        }
    }

    cleanupFinishedSounds(true);
    ma_engine_uninit(&s_engine);
    s_engineReady = false;
}

} // namespace

// ── Config helper (mirrors CapsLockIndicator pattern) ─────────────────────

int VolumeSound::configInt(const std::string& key) {
    static std::unordered_map<std::string, Hyprlang::INT* const*> cache;
    auto it = cache.find(key);
    if (it == cache.end()) {
        auto* cv = HyprlandAPI::getConfigValue(PHANDLE, key);
        if (!cv)
            return 0;
        cache[key] = (Hyprlang::INT* const*)cv->getDataStaticPtr();
        it         = cache.find(key);
    }
    return (int)**it->second;
}

// ── Event handler (main thread — only writes to pipe) ─────────────────────

void VolumeSound::onKey(IKeyboard::SKeyEvent ev, Event::SCallbackInfo& info) {
    (void)info;

    if (ev.state != WL_KEYBOARD_KEY_STATE_PRESSED)
        return;

    // KEY_VOLUMEUP = 115, KEY_VOLUMEDOWN = 114 (Linux evdev)
    if (ev.keycode != 115 && ev.keycode != 114)
        return;

    if (!configInt("plugin:hyprmac:volume_sound_enabled"))
        return;

    // Signal audio thread — non-blocking, never touches PipeWire on main thread
    const char sig = 1;
    write(s_pipeWrite, &sig, 1);
}

// ── Lifecycle ──────────────────────────────────────────────────────────────

void VolumeSound::init() {
    int fds[2];
    if (pipe(fds) != 0)
        return;
    s_pipeRead  = fds[0];
    s_pipeWrite = fds[1];
    fcntl(s_pipeWrite, F_SETFL, O_NONBLOCK);

    s_running.store(true, std::memory_order_release);
    s_audioThread = std::thread(audioThreadMain);

    s_keyListener = Event::bus()->m_events.input.keyboard.key.listen(
        [](IKeyboard::SKeyEvent ev, Event::SCallbackInfo& info) { onKey(ev, info); }
    );
}

void VolumeSound::destroy() {
    s_keyListener.reset();

    s_running.store(false, std::memory_order_release);
    // Poke the thread so it wakes from poll() immediately
    if (s_pipeWrite >= 0) {
        const char wake = 0;
        write(s_pipeWrite, &wake, 1);
    }
    if (s_audioThread.joinable())
        s_audioThread.join();

    if (s_pipeRead  >= 0) { close(s_pipeRead);  s_pipeRead  = -1; }
    if (s_pipeWrite >= 0) { close(s_pipeWrite); s_pipeWrite = -1; }
}
